name: "Generate Cooklang ePUB"
description: "Generate a Cooklang ePUB from a repository containing Cooklang recipe files and templates"
inputs:
  folder:
    description: "folder containing Cooklang recipe files"
    default: "."
  template_glob:
    description: "glob pattern for finding templates"
    default: "templates/*.tmpl"
runs:
  using: "composite"
  steps:
    - uses: robinraju/release-downloader@v1
      with:
        repository: "pakohan/cooklang-epub"
        latest: true
        fileName: "cooklang-epub"
        out-file-path: "${{ runner.temp }}/cooklang-epub"
    - name: make executable
      shell: bash
      run: chmod +x ${{ runner.temp }}/cooklang-epub
    - name: generate epub
      shell: bash
      run: ${{ runner.temp }}/cooklang-epub --folder ${{ inputs.folder }} --output ./recipes.epub --template-files ${{ inputs.template_glob }}
