name: "Generate Cooklang ePUB"
description: "Generate a Cooklang ePUB from a repository containing Cooklang recipe files"
inputs:
  folder:
    description: "folder containing Cooklang recipe files"
    default: "."
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: "stable"
    - name: install binary
      shell: bash
      run: go install github.com/pakohan/cooklang-epub@latest
    - name: generate epub
      shell: bash
      run: cooklang-epub --folder ${{ inputs.folder }} --output ./recipes.epub
    - name: upload epub
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        files: ./recipes.epub
